version: '3.8'
services:

  elastic-query-service-1:
    image: ${GROUP_PROJECT_ID}/elastic-query-service:${SERVICE_VERSION}
    container_name: elastic-query-service-1
    ports:
      - "9105:9105"
    volumes:
      - "./volumes/service-logs:/workspace/elastic-query-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9105 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MS_TWITTER_TO_KAFKA=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "ELASTIC-CONFIG_CONNECTION-URL=http://elastic-1:9200"
      - "SERVER_PORT=9105"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888"
    networks:
      - ${GLOBAL_NETWORK:-services}

  elastic-query-service-2:
    image: ${GROUP_PROJECT_ID}/elastic-query-service:${SERVICE_VERSION}
    container_name: elastic-query-service-2
    ports:
      - "9106:9106"
    volumes:
      - "./volumes/service-logs:/workspace/elastic-query-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9105 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MS_TWITTER_TO_KAFKA=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "ELASTIC-CONFIG_CONNECTION-URL=http://elastic-1:9200"
      - "SERVER_PORT=9106"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888"
    networks:
      - ${GLOBAL_NETWORK:-services}
