version: '3.8'
services:
  elastic-query-web-client:
    image: ${GROUP_PROJECT_ID}/elastic-query-web-client:${SERVICE_VERSION}
    container_name: elastic-query-web-client
    ports:
      - "9104:9104"
    volumes:
      - "./volumes/service-logs:/workspace/elastic-query-web-client/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9104 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MS_TWITTER_TO_KAFKA=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=9104"
      - "SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_BASE-URL=http://elastic-query-service/elastic-query-service/documents"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_ID=elastic-query-service-1"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_HOST=elastic-query-service-1"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_PORT=9105"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_ID=elastic-query-service-2"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_HOST=elastic-query-service-2"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_PORT=9106"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}