version: '3.8'
services:
  
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    platform: linux/amd64
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
