version: '3.8'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    platform: linux/amd64
    ports:
      - "6033:3306"
    volumes:
      - "./volumes/mysql-data/data:/var/lib/mysql"
      - "./volumes/mysql-data/sql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - ${GLOBAL_NETWORK:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - ${GLOBAL_NETWORK:-mysql}