version: '3.8'
services:
  postgres:
    image: binakot/postgresql-postgis-timescaledb:latest
    platform: linux/amd64
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    volumes:
      - "./volumes/postgres-data/data:/var/lib/postgresql/data"
      - "./volumes/postgres-data/sql:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/amd64
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    volumes:
      - "./volumes/pgadmin-data:/var/lib/pgadmin"