version: '3.8'
services:
  elastic-query-web-client:
    image: ${GROUP_PROJECT_ID}/reactive-elastic-query-web-client:${SERVICE_VERSION}
    container_name: reactive-elastic-query-web-client
    ports:
      - "9194:9194"
    volumes:
      - "./volumes/service-logs:/workspace/elastic-query-web-client/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9194 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MS_TWITTER_TO_KAFKA=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=9194"
      - "SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_BASE-URL=http://reactive-elastic-query-service:9183/reactive-elastic-query-service/documents"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
    networks:
      - ${GLOBAL_NETWORK:-services}