version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - ${GLOBAL_NETWORK}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - "./volumes/redis/data:/var/lib/redis"
      - "./volumes/redis/config:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "1979:8081"
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: root
      HTTP_PASSWORD: root
    networks:
      - ${GLOBAL_NETWORK}