version: '3.8'
services:
  twitter-to-kafka-service:
    image: ${GROUP_PROJECT_ID}/twitter-to-kafka-service:${SERVICE_VERSION}
    container_name: twitter-to-kafka-service
    ports:
      - "9101:9101"
    volumes:
      - "./volumes/service-logs:/workspace/twitter-to-kafka-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9101 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MS_TWITTER_TO_KAFKA=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}"
    networks:
      - ${GLOBAL_NETWORK:-services}